#默认80端口
server:
  port: 80
spring:
  profiles:
    #默认是本地环境
    active: local
    include: ${ray.include}
  #模板地址
  thymeleaf:
    prefix: classpath:/templates/
#日志输出文件
logging:
  config: classpath:logback-boot.xml
#mybatis
mybatis:
  #扫描所有实体类
  type-aliases-package: com.learn.dao.entity
  mapper-locations: classpath*:mapper/*.xml
  #配置项
  configuration:
    default-statement-timeout: 3000
    cache-enabled: true
    map-underscore-to-camel-case: true


---
#本地环境
spring:
  profiles: local
  application:
    name: spring-boot-local
    #jdbc
  datasource:
    url: jdbc:mysql://localhost:3306/boot?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
ray:
  include: application-local.yml
---
#测试环境
spring:
  profiles: dev
  application:
      name: spring-boot-dev
    #jdbc
  datasource:
    url: jdbc:mysql://localhost:3306/boot?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root

---
#正式环境
spring:
  profiles: prod
  application:
      name: spring-boot-prod
    #jdbc
  datasource:
    url: jdbc:mysql://localhost:3306/boot?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root