#默认80端口
server:
  port: 80

spring:
    #jdbc
  datasource:
    url: jdbc:mysql://localhost:3306/boot?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root

    #模板地址
  thymeleaf:
    prefix: classpath:/templates/

#日志输出文件
logging:
  config: classpath:logback-boot.xml

#mybatis 只用还使用xml配置写sql才需要用到下面属性
#mybatis.config-location=classpath:mybatis/mybatis-config.xml
#mybatis.type-aliases-package=com.learn.dao.entity
#mybatis.mapper-locations=classpath*:mapper/**/*.xml
