#默认80端口
server:
  port: 80

spring:
    #jdbc
  datasource:
    url: jdbc:mysql://localhost:3306/boot?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root

    #模板地址
  thymeleaf:
    prefix: classpath:/templates/

#日志输出文件
logging:
  config: classpath:logback-boot.xml

#mybatis
mybatis:
  #扫描所有实体类
  type-aliases-package: com.learn.dao.entity
  mapper-locations: classpath*:mapper/*.xml
  #配置项
  configuration:
    default-statement-timeout: 3000
    cache-enabled: true
    map-underscore-to-camel-case: true